Updating Kabanero Logging and Monitoring guides for RHOCP 4.3
kabanero-io/guides pull request #20
Opened 2020-03-25 17:00 UTC by ellen-lau

This PR is to update the current Kabanero Logging and Monitoring guides for RHOCP 4.2 to be compatible for RHOCP 4.3.

The RHOCP 4.2 guides are already compatible for RHOCP 4.3, major differences are changing titles, "tested with" statements, and links to OpenShift guides for 4.3.

For monitoring, a section on "Configure Prometheus Operator to Detect Service Monitors in Other Namespaces" was added that is needed for both RHOCP 4.2 and 4.3 use.

2020-03-25 17:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kabanero-io/guides?pullRequest=20) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kabanero-io/guides?pullRequest=20) before we can accept your contribution.<br/><hr/>**Ellen Lau** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kabanero-io/guides?pullRequest=20) it.</sub>

2020-03-26 14:03 UTC, donbourne requested changes
- at start of the guide it says "Both Prometheus and Grafana can be set up via Operator Lifecycle Manager (OLM)." -- need to mention the CS install choice there as well.
- somewhere, probably just before "Install Prometheus Operator Using Operator Lifecycle Manager (OLM)", there needs to be something explaining that you have 2 choices for setting up Prom/Grafana -- the CS way and the OLM way.  Then explain that if they are using the CS-installed prom/graf they can skip to the section on "Configure Prometheus Operator to Detect Service Monitors in Other Namespaces"
- "The Kubernetes Operator framework is the preferred way to deploy Prometheus on a Kubernetes system. " -- i think we need to stop saying that now as people will think we mean that this is preferable to the CS install approach
- "Create a Service Account with Cluster role and Cluster role binding to ensure you have the permission to get nodes and pods in other namespaces at the cluster scope." - I think we need to clarify this.  I believe it means "ensure Prometheus has permission to make requests to metrics endpoints on pods in other namespaces" -- can you please discuss with Frank and make this statement clearer?
- "Click on Networking > Routes and go to Grafana’s location to see the template dashboard. " - should that say "example" or "sample" dashboard rather than "template"?
- in example yaml fragment under "Prometheus Operator installed via OLM has the MultiNamespace installMode set to false by default, disabling monitoring for more than one namespace, so this must be changed to true.", perhaps add a comment to the yaml above the line you want people to change
- "to add your application’s namespace myapp " -> to add your application’s namespace, for example myapp, 
- add something at the end of the guide to summarize - basically to tell them they have now got prometheus and grafana installed and can access grafana at the grafana route.

2020-03-26 14:03 UTC, donbourne commented on publish/app-logging-ocp-4.2/app-logging-ocp-4.2.md
>  releasedate: 2020-02-19
do you need to update the release date?

2020-03-26 14:03 UTC, donbourne commented on publish/app-logging-ocp-4.2/app-logging-ocp-4.2.md
>  permalink: /guides/app-logging-ocp-4-2/
will permalink change?

2020-03-29 18:40 UTC, donbourne reviewed
move "If you are using the Common Services Prometheus and Grafana monitoring stack, skip to Configure Prometheus Operator to Detect Service Monitors in Other Namespaces." below the section on "Deploy an Application with MP Metrics Endpoint" (since we want people to deploy an app for both approaches).

2020-03-30 18:31 UTC, ellen-lau commented
@jantley-ibm could you please review the content of the updates? Thanks!

2020-03-31 14:10 UTC, donbourne approved these changes

2020-03-31 17:12 UTC, jantley-ibm approved these changes
LGTM

2020-04-08 14:45 UTC, jantley-ibm commented on publish/app-monitoring-ocp-4.2/app-monitoring-ocp-4.2.adoc
> +By default, the Prometheus Operator only watches the namespace it currently resides in, so in order to get the Prometheus Operator to detect Service Monitors created in other namespaces, you must app
recommend changing
Service Monitors
to either
ServiceMonitors
or
service monitors

2020-04-08 14:45 UTC, jantley-ibm reviewed
Just one small recommended change

2020-04-08 14:54 UTC, merged